mod commands;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(commands::remote_pool::RemoteSessionRegistry::default())
        .manage(commands::browse::SearchRegistry::default())
        .manage(commands::terminal::TerminalRegistry::default())
        .manage(commands::transfer::TransferRegistry::default())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            commands::info::info,
            commands::info::capabilities,
            commands::settings::load_terminal_completion_config,
            commands::sessions::test_connection,
            commands::sessions::list_remote_session_states,
            commands::sessions::disconnect_remote_session,
            commands::sessions::list_recent_connections,
            commands::sessions::remember_recent_connection,
            commands::sessions::remove_recent_connection,
            commands::sessions::list_favorites,
            commands::sessions::load_favorite_password,
            commands::sessions::save_favorite,
            commands::sessions::remove_favorite,
            commands::sessions::rename_favorite,
            commands::browse::browse_local,
            commands::browse::browse_remote,
            commands::browse::search_local,
            commands::browse::search_remote,
            commands::browse::cancel_search,
            commands::files::create_local_directory,
            commands::files::create_remote_directory,
            commands::files::rename_local_entry,
            commands::files::rename_remote_entry,
            commands::files::copy_local_entry,
            commands::files::copy_remote_entry,
            commands::files::move_local_entry,
            commands::files::move_remote_entry,
            commands::files::delete_local_entry,
            commands::files::delete_remote_entry,
            commands::files::chmod_local_entry,
            commands::files::chmod_remote_entry,
            commands::files::md5_local_file,
            commands::files::md5_remote_file,
            commands::files::save_local_text_file,
            commands::files::save_remote_text_file,
            commands::open::open_local_entry,
            commands::open::open_remote_entry,
            commands::preview::preview_local_file,
            commands::preview::preview_remote_file,
            commands::terminal::run_local_terminal_command,
            commands::terminal::run_remote_terminal_command,
            commands::terminal::start_local_terminal_session,
            commands::terminal::start_remote_terminal_session,
            commands::terminal::write_terminal_input,
            commands::terminal::resize_terminal_session,
            commands::terminal::close_terminal_session,
            commands::transfer::inspect_upload_conflicts,
            commands::transfer::inspect_download_conflicts,
            commands::transfer::inspect_remote_copy_conflicts,
            commands::transfer::upload_path,
            commands::transfer::download_path,
            commands::transfer::copy_remote_path,
            commands::transfer::cancel_transfer,
        ])
        .run(tauri::generate_context!())
        .expect("error while running rTerm");
}
